// Swiss NPA database — NPA → { city, canton }
// Source: Swiss Post (La Poste Suisse)
// This is a curated list of the most common NPAs

interface NpaEntry {
  city: string
  canton: string
}

const NPA_DB: Record<string, NpaEntry> = {
  // Valais (VS)
  '1890': { city: 'Saint-Maurice', canton: 'VS' },
  '1891': { city: 'Vérossaz', canton: 'VS' },
  '1895': { city: 'Vionnaz', canton: 'VS' },
  '1896': { city: 'Vouvry', canton: 'VS' },
  '1897': { city: 'Le Bouveret', canton: 'VS' },
  '1898': { city: 'Saint-Gingolph', canton: 'VS' },
  '1900': { city: 'Martigny', canton: 'VS' },
  '1902': { city: 'Evionnaz', canton: 'VS' },
  '1903': { city: 'Collonges', canton: 'VS' },
  '1904': { city: 'Vernayaz', canton: 'VS' },
  '1905': { city: 'Dorénaz', canton: 'VS' },
  '1906': { city: 'Charrat', canton: 'VS' },
  '1907': { city: 'Saxon', canton: 'VS' },
  '1908': { city: 'Riddes', canton: 'VS' },
  '1911': { city: 'Ovronnaz', canton: 'VS' },
  '1912': { city: 'Leytron', canton: 'VS' },
  '1913': { city: 'Saillon', canton: 'VS' },
  '1914': { city: 'Isérables', canton: 'VS' },
  '1920': { city: 'Martigny', canton: 'VS' },
  '1921': { city: 'Martigny-Croix', canton: 'VS' },
  '1922': { city: 'Salvan', canton: 'VS' },
  '1923': { city: 'Les Marécottes', canton: 'VS' },
  '1925': { city: 'Finhaut', canton: 'VS' },
  '1926': { city: 'Fully', canton: 'VS' },
  '1927': { city: 'Chemin', canton: 'VS' },
  '1928': { city: 'Ravoire', canton: 'VS' },
  '1929': { city: 'Trient', canton: 'VS' },
  '1933': { city: 'Sembrancher', canton: 'VS' },
  '1934': { city: 'Le Châble', canton: 'VS' },
  '1936': { city: 'Verbier', canton: 'VS' },
  '1937': { city: 'Orsières', canton: 'VS' },
  '1938': { city: 'Champex-Lac', canton: 'VS' },
  '1941': { city: 'Vollèges', canton: 'VS' },
  '1942': { city: 'Levron', canton: 'VS' },
  '1943': { city: 'Praz-de-Fort', canton: 'VS' },
  '1944': { city: 'La Fouly', canton: 'VS' },
  '1945': { city: 'Liddes', canton: 'VS' },
  '1946': { city: 'Bourg-Saint-Pierre', canton: 'VS' },
  '1947': { city: 'Champéry', canton: 'VS' },
  '1948': { city: 'Lourtier', canton: 'VS' },
  '1950': { city: 'Sion', canton: 'VS' },
  '1951': { city: 'Sion', canton: 'VS' },
  '1955': { city: 'Chamoson', canton: 'VS' },
  '1957': { city: 'Ardon', canton: 'VS' },
  '1958': { city: 'Uvrier', canton: 'VS' },
  '1961': { city: 'Haute-Nendaz', canton: 'VS' },
  '1962': { city: 'Pont-de-la-Morge', canton: 'VS' },
  '1963': { city: 'Vétroz', canton: 'VS' },
  '1964': { city: 'Conthey', canton: 'VS' },
  '1965': { city: 'Savièse', canton: 'VS' },
  '1966': { city: 'Ayent', canton: 'VS' },
  '1967': { city: 'Bramois', canton: 'VS' },
  '1968': { city: 'Mase', canton: 'VS' },
  '1969': { city: 'Saint-Martin', canton: 'VS' },
  '1971': { city: 'Grimisuat', canton: 'VS' },
  '1972': { city: 'Anzère', canton: 'VS' },
  '1973': { city: 'Nax', canton: 'VS' },
  '1974': { city: 'Arbaz', canton: 'VS' },
  '1975': { city: 'Saint-Séverin', canton: 'VS' },
  '1976': { city: 'Erde', canton: 'VS' },
  '1977': { city: 'Icogne', canton: 'VS' },
  '1978': { city: 'Lens', canton: 'VS' },
  '1981': { city: 'Vex', canton: 'VS' },
  '1982': { city: 'Euseigne', canton: 'VS' },
  '1983': { city: 'Evolène', canton: 'VS' },
  '1984': { city: 'Les Haudères', canton: 'VS' },
  '1985': { city: 'La Sage', canton: 'VS' },
  '1986': { city: 'Arolla', canton: 'VS' },
  '1987': { city: 'Hérémence', canton: 'VS' },
  '1988': { city: 'Thyon', canton: 'VS' },
  '1991': { city: 'Salins', canton: 'VS' },
  '1992': { city: 'Crête-à-l\'Oeil', canton: 'VS' },
  '1993': { city: 'Veysonnaz', canton: 'VS' },
  '1994': { city: 'Aproz', canton: 'VS' },
  '1996': { city: 'Basse-Nendaz', canton: 'VS' },
  '1997': { city: 'Haute-Nendaz', canton: 'VS' },
  '3900': { city: 'Brig', canton: 'VS' },
  '3901': { city: 'Rothwald', canton: 'VS' },
  '3902': { city: 'Glis', canton: 'VS' },
  '3903': { city: 'Birgisch', canton: 'VS' },
  '3904': { city: 'Naters', canton: 'VS' },
  '3905': { city: 'Saas-Almagell', canton: 'VS' },
  '3906': { city: 'Saas-Fee', canton: 'VS' },
  '3907': { city: 'Simplon Hospiz', canton: 'VS' },
  '3908': { city: 'Saas-Balen', canton: 'VS' },
  '3910': { city: 'Saas-Grund', canton: 'VS' },
  '3911': { city: 'Ried-Brig', canton: 'VS' },
  '3912': { city: 'Termen', canton: 'VS' },
  '3913': { city: 'Rosswald', canton: 'VS' },
  '3914': { city: 'Blatten', canton: 'VS' },
  '3916': { city: 'Ferden', canton: 'VS' },
  '3917': { city: 'Kippel', canton: 'VS' },
  '3918': { city: 'Wiler', canton: 'VS' },
  '3919': { city: 'Blatten', canton: 'VS' },
  '3920': { city: 'Zermatt', canton: 'VS' },
  '3922': { city: 'Stalden', canton: 'VS' },
  '3923': { city: 'Törbel', canton: 'VS' },
  '3924': { city: 'St. Niklaus', canton: 'VS' },
  '3925': { city: 'Grächen', canton: 'VS' },
  '3926': { city: 'Embd', canton: 'VS' },
  '3928': { city: 'Randa', canton: 'VS' },
  '3929': { city: 'Täsch', canton: 'VS' },
  '3930': { city: 'Visp', canton: 'VS' },
  '3931': { city: 'Lalden', canton: 'VS' },
  '3932': { city: 'Visperterminen', canton: 'VS' },
  '3933': { city: 'Staldenried', canton: 'VS' },
  '3934': { city: 'Zeneggen', canton: 'VS' },
  '3935': { city: 'Bürchen', canton: 'VS' },
  '3937': { city: 'Baltschieder', canton: 'VS' },
  '3938': { city: 'Ausserberg', canton: 'VS' },
  '3939': { city: 'Eggerberg', canton: 'VS' },
  '3940': { city: 'Steg', canton: 'VS' },
  '3942': { city: 'Raron', canton: 'VS' },
  '3943': { city: 'Eischoll', canton: 'VS' },
  '3944': { city: 'Unterbäch', canton: 'VS' },
  '3945': { city: 'Gampel', canton: 'VS' },
  '3946': { city: 'Turtmann', canton: 'VS' },
  '3947': { city: 'Ergisch', canton: 'VS' },
  '3948': { city: 'Oberems', canton: 'VS' },
  '3949': { city: 'Hohtenn', canton: 'VS' },
  '3951': { city: 'Agarn', canton: 'VS' },
  '3952': { city: 'Susten', canton: 'VS' },
  '3953': { city: 'Leuk Stadt', canton: 'VS' },
  '3954': { city: 'Leukerbad', canton: 'VS' },
  '3955': { city: 'Albinen', canton: 'VS' },
  '3956': { city: 'Guttet-Feschel', canton: 'VS' },
  '3957': { city: 'Bratsch', canton: 'VS' },
  '3960': { city: 'Sierre', canton: 'VS' },
  '3961': { city: 'Chandolin', canton: 'VS' },
  '3962': { city: 'Montana', canton: 'VS' },
  '3963': { city: 'Crans-Montana', canton: 'VS' },
  '3965': { city: 'Chippis', canton: 'VS' },
  '3966': { city: 'Chalais', canton: 'VS' },
  '3967': { city: 'Vercorin', canton: 'VS' },
  '3968': { city: 'Veyras', canton: 'VS' },
  '3970': { city: 'Salgesch', canton: 'VS' },
  '3971': { city: 'Chermignon', canton: 'VS' },
  '3972': { city: 'Miège', canton: 'VS' },
  '3973': { city: 'Venthône', canton: 'VS' },
  '3974': { city: 'Mollens', canton: 'VS' },
  '3975': { city: 'Randogne', canton: 'VS' },
  '3976': { city: 'Noës', canton: 'VS' },
  '3977': { city: 'Granges', canton: 'VS' },
  '3978': { city: 'Flanthey', canton: 'VS' },
  '3979': { city: 'Grône', canton: 'VS' },
  // Vaud (VD)
  '1000': { city: 'Lausanne', canton: 'VD' },
  '1003': { city: 'Lausanne', canton: 'VD' },
  '1004': { city: 'Lausanne', canton: 'VD' },
  '1005': { city: 'Lausanne', canton: 'VD' },
  '1006': { city: 'Lausanne', canton: 'VD' },
  '1007': { city: 'Lausanne', canton: 'VD' },
  '1008': { city: 'Prilly', canton: 'VD' },
  '1009': { city: 'Pully', canton: 'VD' },
  '1010': { city: 'Lausanne', canton: 'VD' },
  '1011': { city: 'Lausanne', canton: 'VD' },
  '1012': { city: 'Lausanne', canton: 'VD' },
  '1015': { city: 'Lausanne', canton: 'VD' },
  '1018': { city: 'Lausanne', canton: 'VD' },
  '1020': { city: 'Renens', canton: 'VD' },
  '1022': { city: 'Chavannes-Renens', canton: 'VD' },
  '1023': { city: 'Crissier', canton: 'VD' },
  '1024': { city: 'Ecublens', canton: 'VD' },
  '1025': { city: 'Saint-Sulpice', canton: 'VD' },
  '1026': { city: 'Denges', canton: 'VD' },
  '1027': { city: 'Lonay', canton: 'VD' },
  '1028': { city: 'Préverenges', canton: 'VD' },
  '1029': { city: 'Villars-Ste-Croix', canton: 'VD' },
  '1030': { city: 'Bussigny', canton: 'VD' },
  '1032': { city: 'Romanel-sur-Lausanne', canton: 'VD' },
  '1033': { city: 'Cheseaux-sur-Lausanne', canton: 'VD' },
  '1034': { city: 'Boussens', canton: 'VD' },
  '1035': { city: 'Bournens', canton: 'VD' },
  '1036': { city: 'Sullens', canton: 'VD' },
  '1037': { city: 'Etagnières', canton: 'VD' },
  '1038': { city: 'Bercher', canton: 'VD' },
  '1040': { city: 'Echallens', canton: 'VD' },
  '1041': { city: 'Bottens', canton: 'VD' },
  '1042': { city: 'Assens', canton: 'VD' },
  '1052': { city: 'Le Mont-sur-Lausanne', canton: 'VD' },
  '1053': { city: 'Cugy', canton: 'VD' },
  '1054': { city: 'Morrens', canton: 'VD' },
  '1055': { city: 'Froideville', canton: 'VD' },
  '1058': { city: 'Villars-Tiercelin', canton: 'VD' },
  '1059': { city: 'Petagnat', canton: 'VD' },
  '1063': { city: 'Chapelle-sur-Moudon', canton: 'VD' },
  '1066': { city: 'Epalinges', canton: 'VD' },
  '1068': { city: 'Les Monts-de-Pully', canton: 'VD' },
  '1070': { city: 'Puidoux', canton: 'VD' },
  '1071': { city: 'Chexbres', canton: 'VD' },
  '1072': { city: 'Forel', canton: 'VD' },
  '1073': { city: 'Savigny', canton: 'VD' },
  '1076': { city: 'Ferlens', canton: 'VD' },
  '1078': { city: 'Essertes', canton: 'VD' },
  '1080': { city: 'Les Cullayes', canton: 'VD' },
  '1081': { city: 'Montpreveyres', canton: 'VD' },
  '1083': { city: 'Mézières', canton: 'VD' },
  '1084': { city: 'Carrouge', canton: 'VD' },
  '1085': { city: 'Vulliens', canton: 'VD' },
  '1091': { city: 'Grandvaux', canton: 'VD' },
  '1092': { city: 'Belmont-sur-Lausanne', canton: 'VD' },
  '1093': { city: 'La Conversion', canton: 'VD' },
  '1094': { city: 'Paudex', canton: 'VD' },
  '1095': { city: 'Lutry', canton: 'VD' },
  '1096': { city: 'Villette', canton: 'VD' },
  '1097': { city: 'Riex', canton: 'VD' },
  '1098': { city: 'Epesses', canton: 'VD' },
  '1110': { city: 'Morges', canton: 'VD' },
  '1112': { city: 'Echichens', canton: 'VD' },
  '1113': { city: 'St-Saphorin-sur-Morges', canton: 'VD' },
  '1114': { city: 'Colombier', canton: 'VD' },
  '1115': { city: 'Vullierens', canton: 'VD' },
  '1116': { city: 'Cottens', canton: 'VD' },
  '1121': { city: 'Bremblens', canton: 'VD' },
  '1122': { city: 'Romanel-sur-Morges', canton: 'VD' },
  '1125': { city: 'Monnaz', canton: 'VD' },
  '1126': { city: 'Vaux-sur-Morges', canton: 'VD' },
  '1131': { city: 'Tolochenaz', canton: 'VD' },
  '1132': { city: 'Lully', canton: 'VD' },
  '1134': { city: 'Vufflens-le-Château', canton: 'VD' },
  '1135': { city: 'Denens', canton: 'VD' },
  '1136': { city: 'Bussy-Chardonney', canton: 'VD' },
  '1141': { city: 'Sévery', canton: 'VD' },
  '1142': { city: 'Pampigny', canton: 'VD' },
  '1143': { city: 'Apples', canton: 'VD' },
  '1144': { city: 'Ballens', canton: 'VD' },
  '1145': { city: 'Bière', canton: 'VD' },
  '1146': { city: 'Mollens', canton: 'VD' },
  '1147': { city: 'Montricher', canton: 'VD' },
  '1148': { city: 'L\'Isle', canton: 'VD' },
  '1149': { city: 'Berolle', canton: 'VD' },
  '1162': { city: 'Saint-Prex', canton: 'VD' },
  '1163': { city: 'Etoy', canton: 'VD' },
  '1164': { city: 'Buchillon', canton: 'VD' },
  '1165': { city: 'Allaman', canton: 'VD' },
  '1166': { city: 'Perroy', canton: 'VD' },
  '1167': { city: 'Lussy-sur-Morges', canton: 'VD' },
  '1168': { city: 'Villars-sous-Yens', canton: 'VD' },
  '1169': { city: 'Yens', canton: 'VD' },
  '1170': { city: 'Aubonne', canton: 'VD' },
  '1172': { city: 'Bougy-Villars', canton: 'VD' },
  '1173': { city: 'Féchy', canton: 'VD' },
  '1174': { city: 'Montherod', canton: 'VD' },
  '1175': { city: 'Lavigny', canton: 'VD' },
  '1176': { city: 'Saint-Livres', canton: 'VD' },
  '1180': { city: 'Rolle', canton: 'VD' },
  '1182': { city: 'Gilly', canton: 'VD' },
  '1183': { city: 'Bursins', canton: 'VD' },
  '1184': { city: 'Vinzel', canton: 'VD' },
  '1185': { city: 'Mont-sur-Rolle', canton: 'VD' },
  '1186': { city: 'Essertines-sur-Rolle', canton: 'VD' },
  '1187': { city: 'Saint-Oyens', canton: 'VD' },
  '1188': { city: 'Gimel', canton: 'VD' },
  '1189': { city: 'Saubraz', canton: 'VD' },
  '1196': { city: 'Gland', canton: 'VD' },
  '1197': { city: 'Prangins', canton: 'VD' },
  '1260': { city: 'Nyon', canton: 'VD' },
  '1261': { city: 'Longirod', canton: 'VD' },
  '1262': { city: 'Eysins', canton: 'VD' },
  '1263': { city: 'Crassier', canton: 'VD' },
  '1264': { city: 'Saint-Cergue', canton: 'VD' },
  '1266': { city: 'Duillier', canton: 'VD' },
  '1267': { city: 'Coinsins', canton: 'VD' },
  '1268': { city: 'Begnins', canton: 'VD' },
  '1269': { city: 'Bassins', canton: 'VD' },
  '1270': { city: 'Trélex', canton: 'VD' },
  '1271': { city: 'Givrins', canton: 'VD' },
  '1272': { city: 'Genolier', canton: 'VD' },
  '1273': { city: 'Arzier-Le Muids', canton: 'VD' },
  '1274': { city: 'Grens', canton: 'VD' },
  '1275': { city: 'Chéserex', canton: 'VD' },
  '1276': { city: 'Gingins', canton: 'VD' },
  '1277': { city: 'Borex', canton: 'VD' },
  '1278': { city: 'La Rippe', canton: 'VD' },
  '1279': { city: 'Chavannes-de-Bogis', canton: 'VD' },
  '1290': { city: 'Chavannes-des-Bois', canton: 'VD' },
  '1291': { city: 'Commugny', canton: 'VD' },
  '1295': { city: 'Mies', canton: 'VD' },
  '1296': { city: 'Coppet', canton: 'VD' },
  '1297': { city: 'Founex', canton: 'VD' },
  '1299': { city: 'Crans-près-Céligny', canton: 'VD' },
  '1300': { city: 'Ecublens', canton: 'VD' },
  '1302': { city: 'Vufflens-la-Ville', canton: 'VD' },
  '1303': { city: 'Penthaz', canton: 'VD' },
  '1304': { city: 'Cossonay-Ville', canton: 'VD' },
  '1305': { city: 'Penthalaz', canton: 'VD' },
  '1306': { city: 'Daillens', canton: 'VD' },
  '1307': { city: 'Lussery-Villars', canton: 'VD' },
  '1308': { city: 'La Chaux', canton: 'VD' },
  '1312': { city: 'Eclépens', canton: 'VD' },
  '1315': { city: 'La Sarraz', canton: 'VD' },
  '1316': { city: 'Chevilly', canton: 'VD' },
  '1317': { city: 'Orny', canton: 'VD' },
  '1318': { city: 'Pompaples', canton: 'VD' },
  '1321': { city: 'Arnex-sur-Orbe', canton: 'VD' },
  '1322': { city: 'Croy', canton: 'VD' },
  '1323': { city: 'Romainmôtier', canton: 'VD' },
  '1324': { city: 'Premier', canton: 'VD' },
  '1325': { city: 'Vaulion', canton: 'VD' },
  '1326': { city: 'Juriens', canton: 'VD' },
  '1329': { city: 'Bretonières', canton: 'VD' },
  '1337': { city: 'Vallorbe', canton: 'VD' },
  '1338': { city: 'Ballaigues', canton: 'VD' },
  '1341': { city: 'L\'Orient', canton: 'VD' },
  '1342': { city: 'Le Pont', canton: 'VD' },
  '1343': { city: 'Les Charbonnières', canton: 'VD' },
  '1344': { city: 'L\'Abbaye', canton: 'VD' },
  '1345': { city: 'Le Lieu', canton: 'VD' },
  '1346': { city: 'Les Bioux', canton: 'VD' },
  '1347': { city: 'Le Sentier', canton: 'VD' },
  '1348': { city: 'Le Brassus', canton: 'VD' },
  '1350': { city: 'Orbe', canton: 'VD' },
  '1352': { city: 'Agiez', canton: 'VD' },
  '1353': { city: 'Bofflens', canton: 'VD' },
  '1354': { city: 'Montcherand', canton: 'VD' },
  '1355': { city: 'L\'Abergement', canton: 'VD' },
  '1356': { city: 'Les Clées', canton: 'VD' },
  '1357': { city: 'Lignerolle', canton: 'VD' },
  '1358': { city: 'Valeyres-sous-Rances', canton: 'VD' },
  '1400': { city: 'Yverdon-les-Bains', canton: 'VD' },
  '1401': { city: 'Yverdon-les-Bains', canton: 'VD' },
  '1404': { city: 'Villars-Epeney', canton: 'VD' },
  '1405': { city: 'Pomy', canton: 'VD' },
  '1406': { city: 'Cronay', canton: 'VD' },
  '1407': { city: 'Donneloye', canton: 'VD' },
  '1408': { city: 'Prahins', canton: 'VD' },
  '1409': { city: 'Chanéaz', canton: 'VD' },
  '1410': { city: 'Thierrens', canton: 'VD' },
  '1412': { city: 'Ursins', canton: 'VD' },
  '1413': { city: 'Orzens', canton: 'VD' },
  '1415': { city: 'Molondin', canton: 'VD' },
  '1416': { city: 'Pailly', canton: 'VD' },
  '1417': { city: 'Epautheyres', canton: 'VD' },
  '1418': { city: 'Vuarrens', canton: 'VD' },
  '1420': { city: 'Fiez', canton: 'VD' },
  '1421': { city: 'Grandevent', canton: 'VD' },
  '1422': { city: 'Grandson', canton: 'VD' },
  '1423': { city: 'Villars-Burquin', canton: 'VD' },
  '1424': { city: 'Champagne', canton: 'VD' },
  '1425': { city: 'Onnens', canton: 'VD' },
  '1426': { city: 'Concise', canton: 'VD' },
  '1427': { city: 'Bonvillars', canton: 'VD' },
  '1428': { city: 'Mutrux', canton: 'VD' },
  '1429': { city: 'Giez', canton: 'VD' },
  '1430': { city: 'Orges', canton: 'VD' },
  '1431': { city: 'Novalles', canton: 'VD' },
  '1432': { city: 'Belmont-sur-Yverdon', canton: 'VD' },
  '1433': { city: 'Suchy', canton: 'VD' },
  '1434': { city: 'Ependes', canton: 'VD' },
  '1435': { city: 'Essert-Pittet', canton: 'VD' },
  '1436': { city: 'Chamblon', canton: 'VD' },
  '1437': { city: 'Suscévaz', canton: 'VD' },
  '1438': { city: 'Mathod', canton: 'VD' },
  '1440': { city: 'Montagny-Chamard', canton: 'VD' },
  '1441': { city: 'Valeyres-sous-Montagny', canton: 'VD' },
  '1442': { city: 'Montagny-près-Yverdon', canton: 'VD' },
  '1443': { city: 'Champvent', canton: 'VD' },
  '1445': { city: 'Vuiteboeuf', canton: 'VD' },
  '1446': { city: 'Baulmes', canton: 'VD' },
  '1450': { city: 'Ste-Croix', canton: 'VD' },
  '1462': { city: 'Yvonand', canton: 'VD' },
  '1464': { city: 'Chêne-Pâquier', canton: 'VD' },
  '1468': { city: 'Cheyres', canton: 'VD' },
  '1470': { city: 'Estavayer-le-Lac', canton: 'FR' },
  '1510': { city: 'Moudon', canton: 'VD' },
  '1512': { city: 'Chavannes-sur-Moudon', canton: 'VD' },
  '1513': { city: 'Rossinière', canton: 'VD' },
  '1522': { city: 'Lucens', canton: 'VD' },
  '1530': { city: 'Payerne', canton: 'VD' },
  '1535': { city: 'Combremont-le-Grand', canton: 'VD' },
  '1536': { city: 'Combremont-le-Petit', canton: 'VD' },
  '1537': { city: 'Champtauroz', canton: 'VD' },
  '1538': { city: 'Treytorrens', canton: 'VD' },
  '1543': { city: 'Grandcour', canton: 'VD' },
  '1545': { city: 'Chevroux', canton: 'VD' },
  '1551': { city: 'Vers-chez-Perrin', canton: 'VD' },
  '1552': { city: 'Trey', canton: 'VD' },
  '1553': { city: 'Châtonnaye', canton: 'FR' },
  '1554': { city: 'Rossens', canton: 'VD' },
  '1555': { city: 'Villarzel', canton: 'VD' },
  '1562': { city: 'Corcelles-près-Payerne', canton: 'VD' },
  '1580': { city: 'Avenches', canton: 'VD' },
  '1588': { city: 'Cudrefin', canton: 'VD' },
  '1610': { city: 'Oron-la-Ville', canton: 'VD' },
  '1612': { city: 'Ecoteaux', canton: 'VD' },
  '1613': { city: 'Maracon', canton: 'VD' },
  '1614': { city: 'Granges', canton: 'VD' },
  '1615': { city: 'Bossonnens', canton: 'FR' },
  '1616': { city: 'Attalens', canton: 'FR' },
  '1617': { city: 'Remaufens', canton: 'FR' },
  '1618': { city: 'Châtel-St-Denis', canton: 'FR' },
  '1619': { city: 'Les Paccots', canton: 'FR' },
  '1623': { city: 'Semsales', canton: 'FR' },
  '1630': { city: 'Bulle', canton: 'FR' },
  '1632': { city: 'Riaz', canton: 'FR' },
  '1633': { city: 'Marsens', canton: 'FR' },
  '1634': { city: 'La Roche', canton: 'FR' },
  '1635': { city: 'La Tour-de-Trême', canton: 'FR' },
  '1636': { city: 'Broc', canton: 'FR' },
  '1637': { city: 'Charmey', canton: 'FR' },
  '1638': { city: 'Morlon', canton: 'FR' },
  '1642': { city: 'Sorens', canton: 'FR' },
  '1643': { city: 'Gumefens', canton: 'FR' },
  '1644': { city: 'Avry-devant-Pont', canton: 'FR' },
  '1645': { city: 'Le Bry', canton: 'FR' },
  '1646': { city: 'Echarlens', canton: 'FR' },
  '1648': { city: 'Hauteville', canton: 'FR' },
  '1649': { city: 'Pont-la-Ville', canton: 'FR' },
  '1650': { city: 'Botterens', canton: 'FR' },
  '1651': { city: 'Villarvolard', canton: 'FR' },
  '1652': { city: 'Villarbeney', canton: 'FR' },
  '1653': { city: 'Crésuz', canton: 'FR' },
  '1654': { city: 'Cerniat', canton: 'FR' },
  '1656': { city: 'Jaun', canton: 'FR' },
  '1660': { city: 'Château-d\'Oex', canton: 'VD' },
  '1663': { city: 'Gruyères', canton: 'FR' },
  '1669': { city: 'Les Sciernes-d\'Albeuve', canton: 'FR' },
  '1670': { city: 'Ursy', canton: 'FR' },
  '1680': { city: 'Romont', canton: 'FR' },
  '1700': { city: 'Fribourg', canton: 'FR' },
  '1701': { city: 'Fribourg', canton: 'FR' },
  '1708': { city: 'Fribourg', canton: 'FR' },
  '1720': { city: 'Corminboeuf', canton: 'FR' },
  '1721': { city: 'Misery-Courtion', canton: 'FR' },
  '1722': { city: 'Bourguillon', canton: 'FR' },
  '1723': { city: 'Marly', canton: 'FR' },
  '1724': { city: 'Ferpicloz', canton: 'FR' },
  '1725': { city: 'Posieux', canton: 'FR' },
  '1726': { city: 'Farvagny', canton: 'FR' },
  '1727': { city: 'Corpataux-Magnedens', canton: 'FR' },
  '1728': { city: 'Rossens', canton: 'FR' },
  '1730': { city: 'Ecuvillens', canton: 'FR' },
  '1731': { city: 'Ependes', canton: 'FR' },
  '1732': { city: 'Arconciel', canton: 'FR' },
  '1733': { city: 'Treyvaux', canton: 'FR' },
  '1740': { city: 'Neyruz', canton: 'FR' },
  '1741': { city: 'Cottens', canton: 'FR' },
  '1742': { city: 'Autigny', canton: 'FR' },
  '1744': { city: 'Chénens', canton: 'FR' },
  '1745': { city: 'Lentigny', canton: 'FR' },
  '1746': { city: 'Prez-vers-Noréaz', canton: 'FR' },
  '1747': { city: 'Corserey', canton: 'FR' },
  '1748': { city: 'Torny-le-Grand', canton: 'FR' },
  '1752': { city: 'Villars-sur-Glâne', canton: 'FR' },
  '1753': { city: 'Matran', canton: 'FR' },
  '1754': { city: 'Avry-sur-Matran', canton: 'FR' },
  '1756': { city: 'Lovens', canton: 'FR' },
  '1757': { city: 'Noréaz', canton: 'FR' },
  '1762': { city: 'Givisiez', canton: 'FR' },
  '1763': { city: 'Granges-Paccot', canton: 'FR' },
  '1772': { city: 'Grolley', canton: 'FR' },
  '1773': { city: 'Léchelles', canton: 'FR' },
  '1774': { city: 'Cousset', canton: 'FR' },
  '1775': { city: 'Grandsivaz', canton: 'FR' },
  '1776': { city: 'Montagny-la-Ville', canton: 'FR' },
  '1782': { city: 'Belfaux', canton: 'FR' },
  '1783': { city: 'Pensier', canton: 'FR' },
  '1784': { city: 'Courtepin', canton: 'FR' },
  '1786': { city: 'Sugiez', canton: 'FR' },
  '1787': { city: 'Môtier', canton: 'FR' },
  '1788': { city: 'Praz', canton: 'FR' },
  '1789': { city: 'Lugnorre', canton: 'FR' },
  '1800': { city: 'Vevey', canton: 'VD' },
  '1801': { city: 'Le Mont-Pèlerin', canton: 'VD' },
  '1802': { city: 'Corseaux', canton: 'VD' },
  '1803': { city: 'Chardonne', canton: 'VD' },
  '1804': { city: 'Corsier-sur-Vevey', canton: 'VD' },
  '1805': { city: 'Jongny', canton: 'VD' },
  '1806': { city: 'St-Légier-La Chiésaz', canton: 'VD' },
  '1807': { city: 'Blonay', canton: 'VD' },
  '1808': { city: 'Les Monts-de-Corsier', canton: 'VD' },
  '1809': { city: 'Rivaz', canton: 'VD' },
  '1814': { city: 'La Tour-de-Peilz', canton: 'VD' },
  '1815': { city: 'Clarens', canton: 'VD' },
  '1816': { city: 'Chailly-Montreux', canton: 'VD' },
  '1817': { city: 'Brent', canton: 'VD' },
  '1820': { city: 'Montreux', canton: 'VD' },
  '1822': { city: 'Chernex', canton: 'VD' },
  '1823': { city: 'Glion', canton: 'VD' },
  '1824': { city: 'Caux', canton: 'VD' },
  '1832': { city: 'Villard-sur-Chamby', canton: 'VD' },
  '1833': { city: 'Les Avants', canton: 'VD' },
  '1844': { city: 'Villeneuve', canton: 'VD' },
  '1845': { city: 'Noville', canton: 'VD' },
  '1846': { city: 'Chessel', canton: 'VD' },
  '1847': { city: 'Rennaz', canton: 'VD' },
  '1852': { city: 'Roche', canton: 'VD' },
  '1853': { city: 'Yvorne', canton: 'VD' },
  '1854': { city: 'Leysin', canton: 'VD' },
  '1856': { city: 'Corbeyrier', canton: 'VD' },
  '1860': { city: 'Aigle', canton: 'VD' },
  '1862': { city: 'La Comballaz', canton: 'VD' },
  '1863': { city: 'Le Sépey', canton: 'VD' },
  '1865': { city: 'Les Diablerets', canton: 'VD' },
  '1866': { city: 'La Forclaz', canton: 'VD' },
  '1867': { city: 'Ollon', canton: 'VD' },
  '1870': { city: 'Monthey', canton: 'VS' },
  '1871': { city: 'Choëx', canton: 'VS' },
  '1872': { city: 'Troistorrents', canton: 'VS' },
  '1873': { city: 'Val-d\'Illiez', canton: 'VS' },
  '1874': { city: 'Champéry', canton: 'VS' },
  '1875': { city: 'Morgins', canton: 'VS' },
  '1880': { city: 'Bex', canton: 'VD' },
  '1882': { city: 'Gryon', canton: 'VD' },
  '1884': { city: 'Villars-sur-Ollon', canton: 'VD' },
  '1885': { city: 'Chesières', canton: 'VD' },
  // Genève (GE)
  '1200': { city: 'Genève', canton: 'GE' },
  '1201': { city: 'Genève', canton: 'GE' },
  '1202': { city: 'Genève', canton: 'GE' },
  '1203': { city: 'Genève', canton: 'GE' },
  '1204': { city: 'Genève', canton: 'GE' },
  '1205': { city: 'Genève', canton: 'GE' },
  '1206': { city: 'Genève', canton: 'GE' },
  '1207': { city: 'Genève', canton: 'GE' },
  '1208': { city: 'Genève', canton: 'GE' },
  '1209': { city: 'Genève', canton: 'GE' },
  '1210': { city: 'Genève', canton: 'GE' },
  '1211': { city: 'Genève', canton: 'GE' },
  '1212': { city: 'Grand-Lancy', canton: 'GE' },
  '1213': { city: 'Onex', canton: 'GE' },
  '1214': { city: 'Vernier', canton: 'GE' },
  '1215': { city: 'Genève', canton: 'GE' },
  '1216': { city: 'Cointrin', canton: 'GE' },
  '1217': { city: 'Meyrin', canton: 'GE' },
  '1218': { city: 'Le Grand-Saconnex', canton: 'GE' },
  '1219': { city: 'Châtelaine', canton: 'GE' },
  '1220': { city: 'Les Avanchets', canton: 'GE' },
  '1222': { city: 'Vésenaz', canton: 'GE' },
  '1223': { city: 'Cologny', canton: 'GE' },
  '1224': { city: 'Chêne-Bougeries', canton: 'GE' },
  '1225': { city: 'Chêne-Bourg', canton: 'GE' },
  '1226': { city: 'Thônex', canton: 'GE' },
  '1227': { city: 'Carouge', canton: 'GE' },
  '1228': { city: 'Plan-les-Ouates', canton: 'GE' },
  '1231': { city: 'Conches', canton: 'GE' },
  '1232': { city: 'Confignon', canton: 'GE' },
  '1233': { city: 'Bernex', canton: 'GE' },
  '1234': { city: 'Vessy', canton: 'GE' },
  '1236': { city: 'Cartigny', canton: 'GE' },
  '1237': { city: 'Avully', canton: 'GE' },
  '1239': { city: 'Collex-Bossy', canton: 'GE' },
  '1241': { city: 'Puplinge', canton: 'GE' },
  '1242': { city: 'Satigny', canton: 'GE' },
  '1243': { city: 'Presinge', canton: 'GE' },
  '1244': { city: 'Choulex', canton: 'GE' },
  '1245': { city: 'Collonge-Bellerive', canton: 'GE' },
  '1246': { city: 'Corsier', canton: 'GE' },
  '1247': { city: 'Anières', canton: 'GE' },
  '1248': { city: 'Hermance', canton: 'GE' },
  '1251': { city: 'Gy', canton: 'GE' },
  '1252': { city: 'Meinier', canton: 'GE' },
  '1253': { city: 'Vandoeuvres', canton: 'GE' },
  '1254': { city: 'Jussy', canton: 'GE' },
  '1255': { city: 'Veyrier', canton: 'GE' },
  '1256': { city: 'Troinex', canton: 'GE' },
  '1257': { city: 'La Croix-de-Rozon', canton: 'GE' },
  '1258': { city: 'Perly', canton: 'GE' },
  // Neuchâtel (NE)
  '2000': { city: 'Neuchâtel', canton: 'NE' },
  '2001': { city: 'Neuchâtel', canton: 'NE' },
  '2002': { city: 'Neuchâtel', canton: 'NE' },
  '2003': { city: 'Neuchâtel', canton: 'NE' },
  '2006': { city: 'Neuchâtel', canton: 'NE' },
  '2007': { city: 'Neuchâtel', canton: 'NE' },
  '2010': { city: 'Neuchâtel', canton: 'NE' },
  '2012': { city: 'Auvernier', canton: 'NE' },
  '2013': { city: 'Colombier', canton: 'NE' },
  '2014': { city: 'Bôle', canton: 'NE' },
  '2015': { city: 'Areuse', canton: 'NE' },
  '2016': { city: 'Cortaillod', canton: 'NE' },
  '2017': { city: 'Boudry', canton: 'NE' },
  '2019': { city: 'Chambrelien', canton: 'NE' },
  '2022': { city: 'Bevaix', canton: 'NE' },
  '2023': { city: 'Gorgier', canton: 'NE' },
  '2024': { city: 'St-Aubin-Sauges', canton: 'NE' },
  '2025': { city: 'Chez-le-Bart', canton: 'NE' },
  '2027': { city: 'Fresens', canton: 'NE' },
  '2028': { city: 'Vaumarcus', canton: 'NE' },
  '2034': { city: 'Peseux', canton: 'NE' },
  '2035': { city: 'Corcelles', canton: 'NE' },
  '2036': { city: 'Cormondrèche', canton: 'NE' },
  '2037': { city: 'Montmollin', canton: 'NE' },
  '2042': { city: 'Valangin', canton: 'NE' },
  '2043': { city: 'Boudevilliers', canton: 'NE' },
  '2046': { city: 'Fontaines', canton: 'NE' },
  '2052': { city: 'Fontainemelon', canton: 'NE' },
  '2053': { city: 'Cernier', canton: 'NE' },
  '2054': { city: 'Chézard-St-Martin', canton: 'NE' },
  '2056': { city: 'Dombresson', canton: 'NE' },
  '2057': { city: 'Villiers', canton: 'NE' },
  '2058': { city: 'Le Pâquier', canton: 'NE' },
  '2063': { city: 'Vilars', canton: 'NE' },
  '2065': { city: 'Savagnier', canton: 'NE' },
  '2067': { city: 'Chaumont', canton: 'NE' },
  '2068': { city: 'Hauterive', canton: 'NE' },
  '2072': { city: 'Saint-Blaise', canton: 'NE' },
  '2073': { city: 'Enges', canton: 'NE' },
  '2074': { city: 'Marin-Epagnier', canton: 'NE' },
  '2075': { city: 'Thielle-Wavre', canton: 'NE' },
  '2087': { city: 'Cornaux', canton: 'NE' },
  '2088': { city: 'Cressier', canton: 'NE' },
  '2103': { city: 'Noiraigue', canton: 'NE' },
  '2105': { city: 'Travers', canton: 'NE' },
  '2108': { city: 'Couvet', canton: 'NE' },
  '2112': { city: 'Môtiers', canton: 'NE' },
  '2113': { city: 'Boveresse', canton: 'NE' },
  '2114': { city: 'Fleurier', canton: 'NE' },
  '2115': { city: 'Buttes', canton: 'NE' },
  '2117': { city: 'La Côte-aux-Fées', canton: 'NE' },
  '2149': { city: 'Champ-du-Moulin', canton: 'NE' },
  '2300': { city: 'La Chaux-de-Fonds', canton: 'NE' },
  '2301': { city: 'La Chaux-de-Fonds', canton: 'NE' },
  '2302': { city: 'La Chaux-de-Fonds', canton: 'NE' },
  '2303': { city: 'La Chaux-de-Fonds', canton: 'NE' },
  '2304': { city: 'La Chaux-de-Fonds', canton: 'NE' },
  '2314': { city: 'La Sagne', canton: 'NE' },
  '2316': { city: 'Les Ponts-de-Martel', canton: 'NE' },
  '2322': { city: 'Le Crêt-du-Locle', canton: 'NE' },
  '2325': { city: 'Les Planchettes', canton: 'NE' },
  '2333': { city: 'La Ferrière', canton: 'BE' },
  '2336': { city: 'Les Bois', canton: 'JU' },
  '2338': { city: 'Les Emibois', canton: 'JU' },
  '2340': { city: 'Le Noirmont', canton: 'JU' },
  '2345': { city: 'Les Breuleux', canton: 'JU' },
  '2350': { city: 'Saignelégier', canton: 'JU' },
  '2360': { city: 'Le Bémont', canton: 'JU' },
  '2400': { city: 'Le Locle', canton: 'NE' },
  '2405': { city: 'La Chaux-du-Milieu', canton: 'NE' },
  '2406': { city: 'La Brévine', canton: 'NE' },
  // Bern (BE)
  '3000': { city: 'Bern', canton: 'BE' },
  '3001': { city: 'Bern', canton: 'BE' },
  '3004': { city: 'Bern', canton: 'BE' },
  '3005': { city: 'Bern', canton: 'BE' },
  '3006': { city: 'Bern', canton: 'BE' },
  '3007': { city: 'Bern', canton: 'BE' },
  '3008': { city: 'Bern', canton: 'BE' },
  '3010': { city: 'Bern', canton: 'BE' },
  '3011': { city: 'Bern', canton: 'BE' },
  '3012': { city: 'Bern', canton: 'BE' },
  '3013': { city: 'Bern', canton: 'BE' },
  '3014': { city: 'Bern', canton: 'BE' },
  '3015': { city: 'Bern', canton: 'BE' },
  '3018': { city: 'Bern', canton: 'BE' },
  '3027': { city: 'Bern', canton: 'BE' },
  '3030': { city: 'Bern', canton: 'BE' },
  '3072': { city: 'Ostermundigen', canton: 'BE' },
  '3073': { city: 'Gümligen', canton: 'BE' },
  '3074': { city: 'Muri bei Bern', canton: 'BE' },
  '3084': { city: 'Wabern', canton: 'BE' },
  '3098': { city: 'Köniz', canton: 'BE' },
  '3110': { city: 'Münsingen', canton: 'BE' },
  '3150': { city: 'Schwarzenburg', canton: 'BE' },
  '3173': { city: 'Oberwangen bei Bern', canton: 'BE' },
  '3176': { city: 'Neuenegg', canton: 'BE' },
  '3178': { city: 'Bösingen', canton: 'FR' },
  '3250': { city: 'Lyss', canton: 'BE' },
  '3270': { city: 'Aarberg', canton: 'BE' },
  '3280': { city: 'Murten', canton: 'FR' },
  '3400': { city: 'Burgdorf', canton: 'BE' },
  '3600': { city: 'Thun', canton: 'BE' },
  '3700': { city: 'Spiez', canton: 'BE' },
  '3800': { city: 'Interlaken', canton: 'BE' },
  '3818': { city: 'Grindelwald', canton: 'BE' },
  '3822': { city: 'Lauterbrunnen', canton: 'BE' },
  '3823': { city: 'Wengen', canton: 'BE' },
  '3825': { city: 'Mürren', canton: 'BE' },
  // Zurich (ZH)
  '8000': { city: 'Zürich', canton: 'ZH' },
  '8001': { city: 'Zürich', canton: 'ZH' },
  '8002': { city: 'Zürich', canton: 'ZH' },
  '8003': { city: 'Zürich', canton: 'ZH' },
  '8004': { city: 'Zürich', canton: 'ZH' },
  '8005': { city: 'Zürich', canton: 'ZH' },
  '8006': { city: 'Zürich', canton: 'ZH' },
  '8008': { city: 'Zürich', canton: 'ZH' },
  '8032': { city: 'Zürich', canton: 'ZH' },
  '8037': { city: 'Zürich', canton: 'ZH' },
  '8038': { city: 'Zürich', canton: 'ZH' },
  '8041': { city: 'Zürich', canton: 'ZH' },
  '8044': { city: 'Zürich', canton: 'ZH' },
  '8045': { city: 'Zürich', canton: 'ZH' },
  '8046': { city: 'Zürich', canton: 'ZH' },
  '8047': { city: 'Zürich', canton: 'ZH' },
  '8048': { city: 'Zürich', canton: 'ZH' },
  '8049': { city: 'Zürich', canton: 'ZH' },
  '8050': { city: 'Zürich', canton: 'ZH' },
  '8051': { city: 'Zürich', canton: 'ZH' },
  '8052': { city: 'Zürich', canton: 'ZH' },
  '8053': { city: 'Zürich', canton: 'ZH' },
  '8055': { city: 'Zürich', canton: 'ZH' },
  '8057': { city: 'Zürich', canton: 'ZH' },
  '8102': { city: 'Oberengstringen', canton: 'ZH' },
  '8103': { city: 'Unterengstringen', canton: 'ZH' },
  '8104': { city: 'Weiningen', canton: 'ZH' },
  '8105': { city: 'Regensdorf', canton: 'ZH' },
  '8112': { city: 'Otelfingen', canton: 'ZH' },
  '8114': { city: 'Dänikon', canton: 'ZH' },
  '8117': { city: 'Fällanden', canton: 'ZH' },
  '8118': { city: 'Pfaffhausen', canton: 'ZH' },
  '8121': { city: 'Benglen', canton: 'ZH' },
  '8122': { city: 'Binz', canton: 'ZH' },
  '8123': { city: 'Ebmatingen', canton: 'ZH' },
  '8124': { city: 'Maur', canton: 'ZH' },
  '8125': { city: 'Zollikerberg', canton: 'ZH' },
  '8126': { city: 'Zumikon', canton: 'ZH' },
  '8127': { city: 'Forch', canton: 'ZH' },
  '8132': { city: 'Egg bei Zürich', canton: 'ZH' },
  '8134': { city: 'Adliswil', canton: 'ZH' },
  '8135': { city: 'Langnau am Albis', canton: 'ZH' },
  '8136': { city: 'Gattikon', canton: 'ZH' },
  '8142': { city: 'Uitikon', canton: 'ZH' },
  '8143': { city: 'Stallikon', canton: 'ZH' },
  '8152': { city: 'Glattbrugg', canton: 'ZH' },
  '8153': { city: 'Rümlang', canton: 'ZH' },
  '8155': { city: 'Niederhasli', canton: 'ZH' },
  '8157': { city: 'Dielsdorf', canton: 'ZH' },
  '8162': { city: 'Steinmaur', canton: 'ZH' },
  '8180': { city: 'Bülach', canton: 'ZH' },
  '8200': { city: 'Schaffhausen', canton: 'SH' },
  '8212': { city: 'Neuhausen am Rheinfall', canton: 'SH' },
  '8240': { city: 'Thayngen', canton: 'SH' },
  '8245': { city: 'Feuerthalen', canton: 'ZH' },
  '8302': { city: 'Kloten', canton: 'ZH' },
  '8303': { city: 'Bassersdorf', canton: 'ZH' },
  '8304': { city: 'Wallisellen', canton: 'ZH' },
  '8305': { city: 'Dietlikon', canton: 'ZH' },
  '8306': { city: 'Brüttisellen', canton: 'ZH' },
  '8307': { city: 'Effretikon', canton: 'ZH' },
  '8310': { city: 'Kemptthal', canton: 'ZH' },
  '8320': { city: 'Fehraltorf', canton: 'ZH' },
  '8330': { city: 'Pfäffikon', canton: 'ZH' },
  '8340': { city: 'Hinwil', canton: 'ZH' },
  '8400': { city: 'Winterthur', canton: 'ZH' },
  '8404': { city: 'Winterthur', canton: 'ZH' },
  '8406': { city: 'Winterthur', canton: 'ZH' },
  '8500': { city: 'Frauenfeld', canton: 'TG' },
  '8570': { city: 'Weinfelden', canton: 'TG' },
  '8580': { city: 'Amriswil', canton: 'TG' },
  '8590': { city: 'Romanshorn', canton: 'TG' },
  '8600': { city: 'Dübendorf', canton: 'ZH' },
  '8610': { city: 'Uster', canton: 'ZH' },
  '8620': { city: 'Wetzikon', canton: 'ZH' },
  '8700': { city: 'Küsnacht', canton: 'ZH' },
  '8702': { city: 'Zollikon', canton: 'ZH' },
  '8706': { city: 'Meilen', canton: 'ZH' },
  '8712': { city: 'Stäfa', canton: 'ZH' },
  '8800': { city: 'Thalwil', canton: 'ZH' },
  '8802': { city: 'Kilchberg', canton: 'ZH' },
  '8803': { city: 'Rüschlikon', canton: 'ZH' },
  '8804': { city: 'Au', canton: 'ZH' },
  '8805': { city: 'Richterswil', canton: 'ZH' },
  '8810': { city: 'Horgen', canton: 'ZH' },
  '8820': { city: 'Wädenswil', canton: 'ZH' },
  '8832': { city: 'Wollerau', canton: 'SZ' },
  '8840': { city: 'Einsiedeln', canton: 'SZ' },
  '8853': { city: 'Lachen', canton: 'SZ' },
  '8854': { city: 'Siebnen', canton: 'SZ' },
  '8856': { city: 'Tuggen', canton: 'SZ' },
  '8857': { city: 'Vorderthal', canton: 'SZ' },
  '8862': { city: 'Schübelbach', canton: 'SZ' },
  '8866': { city: 'Ziegelbrücke', canton: 'GL' },
  '8867': { city: 'Niederurnen', canton: 'GL' },
  '8872': { city: 'Weesen', canton: 'SG' },
  '8880': { city: 'Walenstadt', canton: 'SG' },
  '8890': { city: 'Flums', canton: 'SG' },
  '8898': { city: 'Flumserberg Tannenheim', canton: 'SG' },
  // Basel (BS/BL)
  '4000': { city: 'Basel', canton: 'BS' },
  '4001': { city: 'Basel', canton: 'BS' },
  '4051': { city: 'Basel', canton: 'BS' },
  '4052': { city: 'Basel', canton: 'BS' },
  '4053': { city: 'Basel', canton: 'BS' },
  '4054': { city: 'Basel', canton: 'BS' },
  '4055': { city: 'Basel', canton: 'BS' },
  '4056': { city: 'Basel', canton: 'BS' },
  '4057': { city: 'Basel', canton: 'BS' },
  '4058': { city: 'Basel', canton: 'BS' },
  '4059': { city: 'Basel', canton: 'BS' },
  '4123': { city: 'Allschwil', canton: 'BL' },
  '4125': { city: 'Riehen', canton: 'BS' },
  '4127': { city: 'Birsfelden', canton: 'BL' },
  '4132': { city: 'Muttenz', canton: 'BL' },
  '4133': { city: 'Pratteln', canton: 'BL' },
  '4142': { city: 'Münchenstein', canton: 'BL' },
  '4153': { city: 'Reinach', canton: 'BL' },
  '4242': { city: 'Laufen', canton: 'BL' },
  '4410': { city: 'Liestal', canton: 'BL' },
  // Luzern (LU)
  '6000': { city: 'Luzern', canton: 'LU' },
  '6003': { city: 'Luzern', canton: 'LU' },
  '6004': { city: 'Luzern', canton: 'LU' },
  '6005': { city: 'Luzern', canton: 'LU' },
  '6006': { city: 'Luzern', canton: 'LU' },
  '6010': { city: 'Kriens', canton: 'LU' },
  '6012': { city: 'Obernau', canton: 'LU' },
  '6014': { city: 'Luzern', canton: 'LU' },
  '6015': { city: 'Luzern', canton: 'LU' },
  '6020': { city: 'Emmenbrücke', canton: 'LU' },
  '6030': { city: 'Ebikon', canton: 'LU' },
  '6032': { city: 'Emmen', canton: 'LU' },
  '6033': { city: 'Buchrain', canton: 'LU' },
  '6034': { city: 'Inwil', canton: 'LU' },
  '6036': { city: 'Dierikon', canton: 'LU' },
  '6037': { city: 'Root', canton: 'LU' },
  '6038': { city: 'Gisikon', canton: 'LU' },
  '6039': { city: 'Root Längenbold', canton: 'LU' },
  '6042': { city: 'Dietwil', canton: 'AG' },
  '6043': { city: 'Adligenswil', canton: 'LU' },
  '6045': { city: 'Meggen', canton: 'LU' },
  '6047': { city: 'Kastanienbaum', canton: 'LU' },
  '6048': { city: 'Horw', canton: 'LU' },
  '6052': { city: 'Hergiswil', canton: 'NW' },
  '6300': { city: 'Zug', canton: 'ZG' },
  '6330': { city: 'Cham', canton: 'ZG' },
  '6340': { city: 'Baar', canton: 'ZG' },
  // St. Gallen (SG)
  '9000': { city: 'St. Gallen', canton: 'SG' },
  '9008': { city: 'St. Gallen', canton: 'SG' },
  '9010': { city: 'St. Gallen', canton: 'SG' },
  '9011': { city: 'St. Gallen', canton: 'SG' },
  '9012': { city: 'St. Gallen', canton: 'SG' },
  '9014': { city: 'St. Gallen', canton: 'SG' },
  '9015': { city: 'St. Gallen', canton: 'SG' },
  '9016': { city: 'St. Gallen', canton: 'SG' },
  // Ticino (TI)
  '6500': { city: 'Bellinzona', canton: 'TI' },
  '6600': { city: 'Locarno', canton: 'TI' },
  '6612': { city: 'Ascona', canton: 'TI' },
  '6614': { city: 'Brissago', canton: 'TI' },
  '6646': { city: 'Contra', canton: 'TI' },
  '6648': { city: 'Minusio', canton: 'TI' },
  '6653': { city: 'Verscio', canton: 'TI' },
  '6670': { city: 'Avegno', canton: 'TI' },
  '6900': { city: 'Lugano', canton: 'TI' },
  '6901': { city: 'Lugano', canton: 'TI' },
  '6902': { city: 'Paradiso', canton: 'TI' },
  '6903': { city: 'Lugano', canton: 'TI' },
  '6904': { city: 'Lugano', canton: 'TI' },
  '6906': { city: 'Lugano', canton: 'TI' },
  '6907': { city: 'Lugano', canton: 'TI' },
  '6908': { city: 'Massagno', canton: 'TI' },
  '6912': { city: 'Lugano', canton: 'TI' },
  '6914': { city: 'Carona', canton: 'TI' },
  '6916': { city: 'Grancia', canton: 'TI' },
  '6917': { city: 'Barbengo', canton: 'TI' },
  '6918': { city: 'Figino', canton: 'TI' },
  '6919': { city: 'Caslano', canton: 'TI' },
  '6921': { city: 'Vico Morcote', canton: 'TI' },
  '6922': { city: 'Morcote', canton: 'TI' },
  '6924': { city: 'Sorengo', canton: 'TI' },
  '6926': { city: 'Montagnola', canton: 'TI' },
  '6928': { city: 'Manno', canton: 'TI' },
  '6929': { city: 'Gravesano', canton: 'TI' },
  '6930': { city: 'Bedano', canton: 'TI' },
  '6932': { city: 'Breganzona', canton: 'TI' },
  '6933': { city: 'Muzzano', canton: 'TI' },
  '6934': { city: 'Bioggio', canton: 'TI' },
  '6935': { city: 'Bosco Luganese', canton: 'TI' },
  '6936': { city: 'Cademario', canton: 'TI' },
  '6937': { city: 'Breno', canton: 'TI' },
  '6938': { city: 'Vezio', canton: 'TI' },
  '6939': { city: 'Arosio', canton: 'TI' },
  '6942': { city: 'Savosa', canton: 'TI' },
  '6943': { city: 'Vezia', canton: 'TI' },
  '6944': { city: 'Cureglia', canton: 'TI' },
  '6945': { city: 'Origlio', canton: 'TI' },
  '6946': { city: 'Ponte Capriasca', canton: 'TI' },
  '6947': { city: 'Vaglio', canton: 'TI' },
  '6948': { city: 'Porza', canton: 'TI' },
  '6949': { city: 'Comano', canton: 'TI' },
  '6950': { city: 'Tesserete', canton: 'TI' },
  '6952': { city: 'Canobbio', canton: 'TI' },
  // Grisons (GR)
  '7000': { city: 'Chur', canton: 'GR' },
  '7012': { city: 'Felsberg', canton: 'GR' },
  '7013': { city: 'Domat/Ems', canton: 'GR' },
  '7050': { city: 'Arosa', canton: 'GR' },
  '7078': { city: 'Lenzerheide', canton: 'GR' },
  '7260': { city: 'Davos Dorf', canton: 'GR' },
  '7270': { city: 'Davos Platz', canton: 'GR' },
  '7500': { city: 'St. Moritz', canton: 'GR' },
  '7502': { city: 'Bever', canton: 'GR' },
  '7503': { city: 'Samedan', canton: 'GR' },
  '7504': { city: 'Pontresina', canton: 'GR' },
  '7505': { city: 'Celerina', canton: 'GR' },
  '7512': { city: 'Champfèr', canton: 'GR' },
  '7513': { city: 'Silvaplana', canton: 'GR' },
  '7514': { city: 'Sils im Engadin', canton: 'GR' },
  '7515': { city: 'Sils-Baselgia', canton: 'GR' },
  '7517': { city: 'Maloja', canton: 'GR' },
  '7522': { city: 'La Punt-Chamues-ch', canton: 'GR' },
  '7523': { city: 'Madulain', canton: 'GR' },
  '7524': { city: 'Zuoz', canton: 'GR' },
  '7525': { city: 'S-chanf', canton: 'GR' },
  // Aargau (AG)
  '5000': { city: 'Aarau', canton: 'AG' },
  '5001': { city: 'Aarau', canton: 'AG' },
  '5004': { city: 'Aarau', canton: 'AG' },
  '5012': { city: 'Schönenwerd', canton: 'SO' },
  '5014': { city: 'Gretzenbach', canton: 'SO' },
  '5015': { city: 'Erlinsbach', canton: 'SO' },
  '5018': { city: 'Erlinsbach', canton: 'AG' },
  '5034': { city: 'Suhr', canton: 'AG' },
  '5035': { city: 'Unterentfelden', canton: 'AG' },
  '5036': { city: 'Oberentfelden', canton: 'AG' },
  '5037': { city: 'Muhen', canton: 'AG' },
  '5040': { city: 'Schöftland', canton: 'AG' },
  '5200': { city: 'Brugg', canton: 'AG' },
  '5210': { city: 'Windisch', canton: 'AG' },
  '5223': { city: 'Riniken', canton: 'AG' },
  '5234': { city: 'Villigen', canton: 'AG' },
  '5242': { city: 'Birr', canton: 'AG' },
  '5243': { city: 'Mülligen', canton: 'AG' },
  '5244': { city: 'Birrhard', canton: 'AG' },
  '5245': { city: 'Habsburg', canton: 'AG' },
  '5246': { city: 'Scherz', canton: 'AG' },
  '5300': { city: 'Turgi', canton: 'AG' },
  '5400': { city: 'Baden', canton: 'AG' },
  '5401': { city: 'Baden', canton: 'AG' },
  '5404': { city: 'Baden', canton: 'AG' },
  '5405': { city: 'Dättwil', canton: 'AG' },
  '5406': { city: 'Rütihof', canton: 'AG' },
  '5408': { city: 'Ennetbaden', canton: 'AG' },
  '5412': { city: 'Gebenstorf', canton: 'AG' },
  '5415': { city: 'Nussbaumen bei Baden', canton: 'AG' },
  '5416': { city: 'Kirchdorf', canton: 'AG' },
  '5417': { city: 'Untersiggenthal', canton: 'AG' },
  '5430': { city: 'Wettingen', canton: 'AG' },
  '5432': { city: 'Neuenhof', canton: 'AG' },
  '5436': { city: 'Würenlos', canton: 'AG' },
  '5443': { city: 'Niederrohrdorf', canton: 'AG' },
  '5452': { city: 'Oberrohrdorf', canton: 'AG' },
  '5453': { city: 'Remetschwil', canton: 'AG' },
  '5454': { city: 'Bellikon', canton: 'AG' },
  '5506': { city: 'Mägenwil', canton: 'AG' },
  '5507': { city: 'Mellingen', canton: 'AG' },
  '5600': { city: 'Lenzburg', canton: 'AG' },
  // Solothurn (SO)
  '4500': { city: 'Solothurn', canton: 'SO' },
  '4502': { city: 'Solothurn', canton: 'SO' },
  '4503': { city: 'Solothurn', canton: 'SO' },
  '4512': { city: 'Bellach', canton: 'SO' },
  '4528': { city: 'Zuchwil', canton: 'SO' },
  '4600': { city: 'Olten', canton: 'SO' },
  '4612': { city: 'Wangen bei Olten', canton: 'SO' },
  '4614': { city: 'Hägendorf', canton: 'SO' },
  '4616': { city: 'Kappel', canton: 'SO' },
  '4618': { city: 'Boningen', canton: 'SO' },
  '4625': { city: 'Oberbuchsiten', canton: 'SO' },
  '4632': { city: 'Trimbach', canton: 'SO' },
  '4702': { city: 'Oensingen', canton: 'SO' },
  '4710': { city: 'Balsthal', canton: 'SO' },
  // Jura (JU)
  '2800': { city: 'Delémont', canton: 'JU' },
  '2802': { city: 'Develier', canton: 'JU' },
  '2803': { city: 'Bourrignon', canton: 'JU' },
  '2805': { city: 'Soyhières', canton: 'JU' },
  '2812': { city: 'Movelier', canton: 'JU' },
  '2822': { city: 'Courroux', canton: 'JU' },
  '2830': { city: 'Courrendlin', canton: 'JU' },
  '2842': { city: 'Rossemaison', canton: 'JU' },
  '2852': { city: 'Courtételle', canton: 'JU' },
  '2853': { city: 'Courfaivre', canton: 'JU' },
  '2854': { city: 'Bassecourt', canton: 'JU' },
  '2855': { city: 'Glovelier', canton: 'JU' },
  '2856': { city: 'Boécourt', canton: 'JU' },
  '2857': { city: 'Montavon', canton: 'JU' },
  '2863': { city: 'Undervelier', canton: 'JU' },
  '2882': { city: 'St-Ursanne', canton: 'JU' },
  '2900': { city: 'Porrentruy', canton: 'JU' },
  '2902': { city: 'Fontenais', canton: 'JU' },
  '2903': { city: 'Villars-sur-Fontenais', canton: 'JU' },
  '2904': { city: 'Bressaucourt', canton: 'JU' },
  '2905': { city: 'Courtedoux', canton: 'JU' },
  '2906': { city: 'Chevenez', canton: 'JU' },
  '2908': { city: 'Grandfontaine', canton: 'JU' },
  '2912': { city: 'Réclère', canton: 'JU' },
  '2914': { city: 'Damvant', canton: 'JU' },
  '2916': { city: 'Fahy', canton: 'JU' },
  '2922': { city: 'Courchavon', canton: 'JU' },
  '2923': { city: 'Courtemaîche', canton: 'JU' },
  '2924': { city: 'Montignez', canton: 'JU' },
  '2925': { city: 'Buix', canton: 'JU' },
  '2926': { city: 'Boncourt', canton: 'JU' },
  '2932': { city: 'Coeuve', canton: 'JU' },
  '2933': { city: 'Damphreux', canton: 'JU' },
  '2935': { city: 'Beurnevésin', canton: 'JU' },
  '2942': { city: 'Alle', canton: 'JU' },
  '2943': { city: 'Vendlincourt', canton: 'JU' },
  '2944': { city: 'Bonfol', canton: 'JU' },
  '2946': { city: 'Miécourt', canton: 'JU' },
  '2947': { city: 'Charmoille', canton: 'JU' },
  '2950': { city: 'Courgenay', canton: 'JU' },
  '2952': { city: 'Cornol', canton: 'JU' },
  '2953': { city: 'Fregiécourt', canton: 'JU' },
  '2954': { city: 'Asuel', canton: 'JU' },
}

export function lookupNpa(npa: string): NpaEntry | null {
  return NPA_DB[npa] || null
}

export function searchByCity(query: string): { npa: string; city: string; canton: string }[] {
  const q = query.toLowerCase()
  const results: { npa: string; city: string; canton: string }[] = []
  for (const [npa, entry] of Object.entries(NPA_DB)) {
    if (entry.city.toLowerCase().includes(q)) {
      results.push({ npa, ...entry })
    }
  }
  return results.slice(0, 10)
}
